### ISSUE TITLE
hipchatter bug

### ISSUE THREAD

**Issue by DavidStummer** [sjberry/bristol-hipchat#1]
![screen shot 2017-03-08 at 22 24 45](https://cloud.githubusercontent.com/assets/4497624/23728367/58d4fe42-0454-11e7-8215-7a3868e82fea.png)

Fix: add callback. See screenshot
![screen shot 2017-03-08 at 23 11 46](https://cloud.githubusercontent.com/assets/4497624/23728389/6eb7dec8-0454-11e7-9bf8-55829bcfe961.png)

**Comment by sjberry** [comment]
Theoretically this should be resolved. I no longer have a way to verify as my HipChat cloud account has been obsoleted.
